import type { Achievement, DailyTaskDef } from "./types";

export const HEARTS_MAX = 5;
export const XP_PER_CORRECT = 10;
export const EXAM_QUESTION_COUNT = 50;
export const EXAM_TIME_MINUTES = 60;
export const PASS_SCORE = 90;
export const EXAM_PASS_BONUS_XP = 200;
export const DAILY_TASK_REWARD_XP = 100;
export const DAILY_TASK_REWARD_XP_QUESTIONS = 50;
export const ACHIEVEMENT_XP_PER_LEVEL = 100;

export const DAILY_TASKS: DailyTaskDef[] = [
  {
    type: "exam_pass",
    name: "开启连胜",
    icon: "Trophy",
    description: "完成考试且达到90分",
  },
  {
    type: "chapter_practice",
    name: "章节练习",
    icon: "BookOpen",
    description: "完成1个章节练习",
  },
  {
    type: "chapter_correct_50",
    name: "答题达人",
    icon: "Target",
    description: "今日累计答对100题",
  },
  {
    type: "answer_20_questions",
    name: "刷题达人",
    icon: "PenTool",
    description: "今日任意刷题20道",
  },
];

export const ACHIEVEMENTS: Achievement[] = [
  { key: "achievement_1", name: "初出茅庐", description: "获得100经验值" },
  { key: "achievement_2", name: "小试牛刀", description: "获得200经验值" },
  { key: "achievement_3", name: "崭露头角", description: "获得300经验值" },
  { key: "achievement_4", name: "初露锋芒", description: "获得400经验值" },
  { key: "achievement_5", name: "小有成就", description: "获得500经验值" },
  { key: "achievement_6", name: "渐入佳境", description: "获得600经验值" },
  { key: "achievement_7", name: "步步高升", description: "获得700经验值" },
  { key: "achievement_8", name: "突飞猛进", description: "获得800经验值" },
  { key: "achievement_9", name: "日积月累", description: "获得900经验值" },
  { key: "achievement_10", name: "百炼成钢", description: "获得1000经验值" },
  { key: "achievement_11", name: "勤学苦练", description: "获得1100经验值" },
  { key: "achievement_12", name: "孜孜不倦", description: "获得1200经验值" },
  { key: "achievement_13", name: "学富五车", description: "获得1300经验值" },
  { key: "achievement_14", name: "才高八斗", description: "获得1400经验值" },
  { key: "achievement_15", name: "博学多才", description: "获得1500经验值" },
  { key: "achievement_16", name: "满腹经纶", description: "获得1600经验值" },
  { key: "achievement_17", name: "学贯中西", description: "获得1700经验值" },
  { key: "achievement_18", name: "知识渊博", description: "获得1800经验值" },
  { key: "achievement_19", name: "博览群书", description: "获得1900经验值" },
  { key: "achievement_20", name: "学海无涯", description: "获得2000经验值" },
  { key: "achievement_21", name: "持之以恒", description: "获得2100经验值" },
  { key: "achievement_22", name: "锲而不舍", description: "获得2200经验值" },
  { key: "achievement_23", name: "水滴石穿", description: "获得2300经验值" },
  { key: "achievement_24", name: "铁杵成针", description: "获得2400经验值" },
  { key: "achievement_25", name: "愚公移山", description: "获得2500经验值" },
  { key: "achievement_26", name: "精卫填海", description: "获得2600经验值" },
  { key: "achievement_27", name: "夸父逐日", description: "获得2700经验值" },
  { key: "achievement_28", name: "后羿射日", description: "获得2800经验值" },
  { key: "achievement_29", name: "嫦娥奔月", description: "获得2900经验值" },
  { key: "achievement_30", name: "大禹治水", description: "获得3000经验值" },
  { key: "achievement_31", name: "破茧成蝶", description: "获得3100经验值" },
  { key: "achievement_32", name: "涅槃重生", description: "获得3200经验值" },
  { key: "achievement_33", name: "凤凰展翅", description: "获得3300经验值" },
  { key: "achievement_34", name: "龙腾虎跃", description: "获得3400经验值" },
  { key: "achievement_35", name: "鹰击长空", description: "获得3500经验值" },
  { key: "achievement_36", name: "鱼跃龙门", description: "获得3600经验值" },
  { key: "achievement_37", name: "马到成功", description: "获得3700经验值" },
  { key: "achievement_38", name: "一马当先", description: "获得3800经验值" },
  { key: "achievement_39", name: "万马奔腾", description: "获得3900经验值" },
  { key: "achievement_40", name: "天马行空", description: "获得4000经验值" },
  { key: "achievement_41", name: "学无止境", description: "获得4100经验值" },
  { key: "achievement_42", name: "勇攀高峰", description: "获得4200经验值" },
  { key: "achievement_43", name: "登峰造极", description: "获得4300经验值" },
  { key: "achievement_44", name: "炉火纯青", description: "获得4400经验值" },
  { key: "achievement_45", name: "出神入化", description: "获得4500经验值" },
  { key: "achievement_46", name: "鬼斧神工", description: "获得4600经验值" },
  { key: "achievement_47", name: "巧夺天工", description: "获得4700经验值" },
  { key: "achievement_48", name: "独具匠心", description: "获得4800经验值" },
  { key: "achievement_49", name: "别具一格", description: "获得4900经验值" },
  { key: "achievement_50", name: "独树一帜", description: "获得5000经验值" },
  { key: "achievement_51", name: "学霸降临", description: "获得5100经验值" },
  { key: "achievement_52", name: "学神附体", description: "获得5200经验值" },
  { key: "achievement_53", name: "考神保佑", description: "获得5300经验值" },
  { key: "achievement_54", name: "锦鲤附身", description: "获得5400经验值" },
  { key: "achievement_55", name: "欧皇附体", description: "获得5500经验值" },
  { key: "achievement_56", name: "天选之人", description: "获得5600经验值" },
  { key: "achievement_57", name: "人中龙凤", description: "获得5700经验值" },
  { key: "achievement_58", name: "卧龙凤雏", description: "获得5800经验值" },
  { key: "achievement_59", name: "绝世高手", description: "获得5900经验值" },
  { key: "achievement_60", name: "武林至尊", description: "获得6000经验值" },
  { key: "achievement_61", name: "独孤求败", description: "获得6100经验值" },
  { key: "achievement_62", name: "东方不败", description: "获得6200经验值" },
  { key: "achievement_63", name: "天下无双", description: "获得6300经验值" },
  { key: "achievement_64", name: "举世无双", description: "获得6400经验值" },
  { key: "achievement_65", name: "独一无二", description: "获得6500经验值" },
  { key: "achievement_66", name: "无与伦比", description: "获得6600经验值" },
  { key: "achievement_67", name: "空前绝后", description: "获得6700经验值" },
  { key: "achievement_68", name: "前无古人", description: "获得6800经验值" },
  { key: "achievement_69", name: "后无来者", description: "获得6900经验值" },
  { key: "achievement_70", name: "名垂青史", description: "获得7000经验值" },
  { key: "achievement_71", name: "流芳百世", description: "获得7100经验值" },
  { key: "achievement_72", name: "永垂不朽", description: "获得7200经验值" },
  { key: "achievement_73", name: "百世流芳", description: "获得7300经验值" },
  { key: "achievement_74", name: "万古长青", description: "获得7400经验值" },
  { key: "achievement_75", name: "千古流芳", description: "获得7500经验值" },
  { key: "achievement_76", name: "一代宗师", description: "获得7600经验值" },
  { key: "achievement_77", name: "开山鼻祖", description: "获得7700经验值" },
  { key: "achievement_78", name: "泰山北斗", description: "获得7800经验值" },
  { key: "achievement_79", name: "中流砥柱", description: "获得7900经验值" },
  { key: "achievement_80", name: "国之栋梁", description: "获得8000经验值" },
  { key: "achievement_81", name: "学富五车", description: "获得8100经验值" },
  { key: "achievement_82", name: "才高八斗", description: "获得8200经验值" },
  { key: "achievement_83", name: "七步之才", description: "获得8300经验值" },
  { key: "achievement_84", name: "八斗之才", description: "获得8400经验值" },
  { key: "achievement_85", name: "出口成章", description: "获得8500经验值" },
  { key: "achievement_86", name: "下笔成文", description: "获得8600经验值" },
  { key: "achievement_87", name: "妙笔生花", description: "获得8700经验值" },
  { key: "achievement_88", name: "文思泉涌", description: "获得8800经验值" },
  { key: "achievement_89", name: "才华横溢", description: "获得8900经验值" },
  { key: "achievement_90", name: "满腹经纶", description: "获得9000经验值" },
  { key: "achievement_91", name: "学贯古今", description: "获得9100经验值" },
  { key: "achievement_92", name: "博古通今", description: "获得9200经验值" },
  { key: "achievement_93", name: "通今博古", description: "获得9300经验值" },
  { key: "achievement_94", name: "见多识广", description: "获得9400经验值" },
  { key: "achievement_95", name: "阅历丰富", description: "获得9500经验值" },
  { key: "achievement_96", name: "经验老到", description: "获得9600经验值" },
  { key: "achievement_97", name: "老马识途", description: "获得9700经验值" },
  { key: "achievement_98", name: "驾轻就熟", description: "获得9800经验值" },
  { key: "achievement_99", name: "轻车熟路", description: "获得9900经验值" },
  { key: "achievement_100", name: "满级大佬", description: "获得10000经验值" },
];
